owner: mdyd-dev
repo: uptime

sites:
  - name: Sydney
    url: https://prod01.sydney.platformos.com/_status
  - name: Oregon
    url: https://prod01.oregon.platform-os.com/_status
  - name: London
    url: https://prod01.london.platform-os.com/_status
  - name: Oregon Staging
    url: https://staging.oregon.platformos.com/_status
  - name: Partner Portal
    url: https://partners.platformos.com/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.platformos.com
  # baseUrl: /
  name: Uptime
  introTitle: "platformOS status page"
  introMessage: "Learn uptime, average response times, ongoing and past incidents"

i18n:
  footer: Powered by [platformOS](https://www.platformos.com) and [Upptime](https://upptime.js.org)